services:
    _defaults:
        public: true

    numero2_tags.listener.data_container.module:
        class: numero2\TagsBundle\EventListener\DataContainer\ModuleListener
        arguments:
            - '@database_connection'

    numero2_tags.listener.data_container.tags:
        class: numero2\TagsBundle\EventListener\DataContainer\TagsListener

    numero2_tags.listener.news:
        class: numero2\TagsBundle\EventListener\NewsListener