services:
    _defaults:
        autowire: true
        autoconfigure: true


    numero2\TagsBundle\EventSubscriber\KernelRequestSubscriber:
        arguments:
            - '@contao.routing.scope_matcher'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }


    numero2.purgeTagsCommand:
        class: numero2\TagsBundle\Command\PurgeTagsCommand
        public: true
        arguments:
            - '@contao.framework'
        tags:
            - { name: console.command }